mokeyish/smartdns-rs

- src/dns_conf.rs
- src/main.rs
> :art: Dedup bind addr

- src/dns_mw_addr.rs
> test max_reply_ip_num

- TODO.md
- src/dns_client.rs
- src/dns_conf.rs
- src/dns_mw_ns.rs
- src/dns_url.rs
- src/main.rs
- src/trust_dns.rs
Base on https://github.com/bluejekyll/trust-dns/pull/1906
> ✨ Implement Edns client subnet.

- src/config/parser/bytes.rs
- src/config/parser/domain_set_provider.rs
- src/config/parser/ipnet.rs
- src/config/parser/mod.rs
- src/config/parser/speed_mode.rs
> :bug: fix config parsing error

- Cargo.toml
- src/config/parser/nameserver.rs
- src/dns_client.rs
- src/dns_url.rs
- tests/example/smartdns.conf
> ✨ add support for DoH3

- src/api/serve_dns.rs
```sh
curl https://localhost/dns-query?name=example.com&type=A
```
> :art: Allow http get to query DNS

- .gitignore
- .vscode/settings.json
- Cargo.toml
- justfile
- src/api/serve_dns.rs
- src/app.rs
- src/cli.rs
- src/config/domain_set.rs
- src/config/mod.rs
- src/dns.rs
- src/dns_client.rs
- src/dns_conf.rs
- src/dns_mw_addr.rs
- src/dns_mw_cache.rs
- src/dns_mw_ns.rs
- src/dns_mw_zone.rs
- src/infra/ping.rs
- src/main.rs
- src/server/quic.rs
- src/server/tcp.rs
- src/server/tls.rs
- src/server/udp.rs
- Add test configuration subcommand
- Adopt a merge strategy for domain_set with the same name
- Keep CNAME records #199 
- Fastest IP test adds query type check #218 
- Restore whoami PTR query
- DoH supports num record type
> :art: some improvements

- src/config/parser/path.rs
- src/dns_mw_ns.rs
> 🐛 fix windows path parsing

- src/dns_mw_zone.rs
> :bug: PTR query for private IP returns empty records.

- src/dns_mw.rs
- src/dns_mw_addr.rs
> 🐛 Fix max_ip_reply_num when CNAME exists

- src/dns_url.rs
server-https https://dns.cloudflare.com/dns-query#h3
> ✨ Support setting H3 through HTTPS url fragment

- build.rs
- justfile
- src/config/nameserver.rs
- src/config/parser/nameserver.rs
- src/dns_client.rs
- src/infra/mapped_file.rs
> ✨ Add support for binding interface for nameserver

- Cargo.toml
- src/dns.rs
- src/dns_mw_cache.rs
- src/dns_mw_ns.rs
- src/dnsmasq.rs
> 🐛 Add nameserver group verification for cached results

- src/app.rs
- src/dns_mw_hosts.rs
- src/main.rs
> ✨ Add support for resolving hostname

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/main.rs
- src/service/installer.rs
- src/service/service_manager.rs
> 🐛 Fix windows service uninstall failure

- src/config/parser/domain_rule.rs
- src/config/parser/speed_mode.rs
- src/config/speed_mode.rs
- src/dns_mw_ns.rs
> 🐛 Fix `domain-rules -c none ` not work

- src/dns_client.rs
> 🐛 Fix "no connections available" for  default nameserver group

- src/dns_conf.rs
> ✨ Enhance filepath resolving

- src/dns_mw_cname.rs
> 🐛Fix CNAME error DNS_PROBE_FINISHED_NXDOMAIN

- src/dns_mw_cache.rs
This is needed when there are one or more `CNAME` records which need to be in the correct order: the order in which they were resolved by the upstream resolver.
> 🎨 Maintain correct record ordering in cache inserts

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/config/bind_addr.rs
- src/config/mod.rs
- src/config/parser/bind_addr.rs
- src/config/parser/mod.rs
- src/dns_conf.rs
- src/server/h3.rs
- src/server/mod.rs
> ✨ Add support for bind-h3

- .gitignore
- Cargo.lock
- src/app.rs
- src/config/log.rs
- src/dns_conf.rs
- src/log.rs
- src/main.rs
> 🐛 Fix log-console no not work

- src/app.rs
- src/dns_client.rs
- src/main.rs
dnsperf-testing repo：[mokeyish/dnsperf-testing](https://github.com/mokeyish/dnsperf-testing)
- Performance before optimization：
- Performance after optimization
---
[SmartDNS ](https://github.com/pymumu/smartdns) written in C language
> ⚡Enhance performance by 17x

- src/dns_url.rs
> 🐛 Fix mDNS url parsing

- src/config/parser/nameserver.rs
- src/dns_client.rs
- src/dns_url.rs
- src/libdns/custom/connection_provider.rs
- #594 的一部分实现（system）
- 修改了解析代码，先整段解析再切分protocol
- 优化dns_client.rs代码，基本照搬 #628
> Support server system

- README.md
- README_zh-CN.md
Change `help` command to `--help`
> Correct installation guide in README
